line_length: 
 - 500 # warning
 - 1000 # error


disabled_rules:
 - trailing_newline
 - vertical_whitespace
 - trailing_whitespace
 - opening_brace
 - colon
 - statement_position
 - unused_closure_parameter
 - function_parameter_count
 - identifier_name

opt_in_rules:
 - force_unwrapping
 - collection_alignment


force_unwrapping: 
 severity: error # explicitly

